Repository YAPP-Github/PyonsnalColor-iOS, pull requests merged in 2023-11, with the labels that each got.

#133 리뷰 작성을 위한 화면, API호출 구현
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ProductCell/ProductCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Review/StarRatedView.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Review/StarRatingView.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Review/StarView.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/DetailReviewBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/DetailReviewInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/DetailReviewRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/DetailReviewViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/DetailReviewViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/Review.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/Views/ReviewButton.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/Views/SingleLineReview.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Review/ReviewEvaluationKind.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Review/ReviewUploadEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIImage+.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UILabel+.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Config/Config.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Products/ProductAPI.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Products/ProductAPIService.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/PyonsnalColorClient.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_delete_medium.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_delete_medium.imageset/icon_delete(m).svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind+Icon.swift
  Pyonsnal-Color/Pyonsnal-Color/ReviewPopup/ReviewPopupBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ReviewPopup/ReviewPopupInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ReviewPopup/ReviewPopupRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ReviewPopup/ReviewPopupViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ReviewPopup/ReviewPopupViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/StarRatingReview/StarRatingReviewBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/StarRatingReview/StarRatingReviewInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/StarRatingReview/StarRatingReviewRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/StarRatingReview/StarRatingReviewViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/StarRatingReview/StarRatingReviewViewHolder.swift
Labels: feature, UI, d-1

#135 상품 리뷰관련 기능 구현
  Pyonsnal-Color/Pyonsnal-Color/Entity/Products/ProductDetailSectionItem.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Review/ReviewEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/String+.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Products/ProductAPI.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Products/ProductAPIService.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/Subview/ReviewWriteCell/ProductDetailReviewWriteCell.swift
Labels: feature, UI, d-1

#137 리뷰 등록 관련 QA 수정 0.2.0(3)
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/DetailReviewViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/Subview/ReviewMetaView/ReviewMetaView.swift
  Pyonsnal-Color/Pyonsnal-Color/StarRatingReview/StarRatingReviewViewHolder.swift
Labels: bug, d-1

#136 찜하기 기능 QA 수정 0.2.0(3)
  Pyonsnal-Color/Pyonsnal-Color/Favorite/FavoritePageTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Config/Config.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController.swift
Labels: bug, d-1

#139 [디자인 QA] 찜하기 design 수정
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ProductCell/ProductCell+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ProductCell/ProductCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Layout/CommonProductSectionLayout.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/BackNavigationView.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Protocol/CommonProductPageViewControllerRenderable.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Protocol/FavoriteHomeDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Protocol/ProductListDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/EventHomeTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/FavoriteHome/FavoriteHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/FavoriteHome/FavoriteHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/FavoriteHome/FavoriteHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/FavoriteHome/View/FavoriteHomePageTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/FavoriteHome/View/FavoriteHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/FavoriteHome/View/FavoriteHomeViewController+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/FavoriteHome/View/FavoriteHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarComponent.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarRouter.swift
Labels: d-1, QA

#142 [디자인 QA] 이벤트 태그 UI 수정
  Pyonsnal-Color/Pyonsnal-Color/Common/Tag/EventTagBigView.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/icon_like_unselected.imageset/icon_like_unselected.svg
Labels: UI, d-1, QA

#144 검색 화면 업데이트
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchViewController.swift
Labels: feature, UI, d-1

#145 카테고리 필터 팝업 노출 시 애니메이션 수정 및 기능 QA 수정
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/DetailReviewViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/DetailReviewViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/ProductFilterViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchRouter.swift
Labels: bug, d-1
