Repository YAPP-Github/PyonsnalColor-iOS, pull requests merged in 2023-07, with the labels that each got.

#25 이벤트 탭 화면 구현
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ConvenienceStoreCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ProductCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/ClassNameRenderable.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeSectionLayout.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/Cell/EventBannerCell.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/Cell/EventBannerItemCell.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/ItemHeaderTitleView.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/NSObject+.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/EventtHome/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/EventtHome/tag_new.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/EventtHome/tag_new.imageset/tag_new.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/HeaderView/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/HeaderView/bellSimple.imageset/BellSimple.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/HeaderView/bellSimple.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind.swift
Labels: feature, UI, d-n

#32 커스텀 TitleNavigationBar 클래스 생성
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/TitleNavigationView.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewHolder.swift
Labels: UI, d-n

#26 디자인 시스템 - 컬러 추가
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIColor+.swift
Labels: design system, d-n

#34 알림함 리블렛 구현 및 홈화면과 연결
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Extension/DateFormatter+.swift
  Pyonsnal-Color/Pyonsnal-Color/NotificationList/NotificationListBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/NotificationList/NotificationListInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/NotificationList/NotificationListRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/NotificationList/NotificationListViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/NotificationList/NotificationListViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/NotificationList/Views/NotificationCell.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductListViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Notfication/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Notfication/event_tag.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Notfication/event_tag.imageset/Property 1=행사.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Notfication/keyword_tag.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Notfication/keyword_tag.imageset/Property 1=키워드.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Notfication/product_tag.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Notfication/product_tag.imageset/Property 1=차별화.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind.swift
Labels: feature, UI, d-n

#40 NavigationController 생성
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/3rdParty/RIBs+.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarRouter.swift
Labels: feature, architecture, d-n

#38 이미지 네비바 구현
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/ImageNavigationView.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/ImageNavigationViewDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIButton+.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIImageView+.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/HeaderView/icon_back.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/HeaderView/icon_back.imageset/icon_back.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_7Eleven.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_7Eleven.imageset/icon_7Eleven.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_CU.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_CU.imageset/icon_CU.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_Emart24.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_Emart24.imageset/icon_Emart24.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_GS.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_GS.imageset/icon_GS.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind+HeaderView.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind+StoreIcon.swift
Labels: feature, UI, design system, d-1

#43 알림함 구현 (컨플릭 수정)
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/TitleNavigationView.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/TitleNavigationViewDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
Labels: UI

#42 네트워크 레이어 작성 및 애플 로그인 연결
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/Model/ErrorResponse.swift
  Pyonsnal-Color/Pyonsnal-Color/Model/LoginResponseEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Auth/AuthRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Config/Config.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Error/NetworkError.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/NetworkRequestBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/NetworkRequestable.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/PyonsnalColorClient.swift
Labels: feature, d-1

#24 상품 상세 화면 구현 - ProductDetail
  Pyonsnal-Color/.swiftlint.yml
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/ImageNavigationView.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Tag/EventTagBigView.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Tag/NewTagBigView.swift
  Pyonsnal-Color/Pyonsnal-Color/DesignSystem/Spacing.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/EventTag.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/GiftItemEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/ProductEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIColor+.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIView+.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/GiftInformationView.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/GiftItemView.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductTagListView.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/EventtHome/tag_new.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/EventtHome/tag_new.imageset/tag_new.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Info.plist
Labels: feature, UI, d-n

#44 이벤트 상세 페이지 리블렛 생성 및 연결
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/3rdParty/RIBs+.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventDetail/EventDetailBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventDetail/EventDetailInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventDetail/EventDetailRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventDetail/EventDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/Cell/EventBannerCell.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/Cell/EventBannerItemCell.swift
Labels: UI, d-n

#53 로그인 API 구현 및 연동
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Entity/Auth/UserAuthEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/Model/ErrorResponse.swift
  Pyonsnal-Color/Pyonsnal-Color/Model/LoginResponseEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Auth/AuthAPIService.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Auth/AuthRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Config/Config.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/PyonsnalColorClient.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootComponent.swift
Labels: feature, d-0

#54 로그아웃 & 회원탈퇴 시 popup 구현
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/AccountSetting/AccountSettingBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/AccountSetting/AccountSettingInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/AccountSetting/AccountSettingRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/AccountSetting/AccountSettingViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIButton+.swift
  Pyonsnal-Color/Pyonsnal-Color/LogoutPopup/LogoutPopupBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/LogoutPopup/LogoutPopupInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/LogoutPopup/LogoutPopupRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/LogoutPopup/LogoutPopupViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeRouter.swift
Labels: feature, UI, d-1

#50 Feature/#39 terms of use UI
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/Button/PrimaryButton.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/BackNavigationView.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/BackNavigationViewDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/CommonWeb/CommonWebBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/CommonWeb/CommonWebInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/CommonWeb/CommonWebRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/CommonWeb/CommonWebViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventDetail/EventDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIButton+.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIView+.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/check.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/check.imageset/check.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/check.selected.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/check.selected.imageset/check.selected.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/icon_arrow.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/icon_arrow.imageset/icon_detail.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/icon_close.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/icon_close.imageset/icon_close.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/UrlConstant/ProfileUrl.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/UrlConstant/TermsOfUseUrl.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/TermsOfUse/SubTerms.swift
  Pyonsnal-Color/Pyonsnal-Color/TermsOfUse/TermsOfUseBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/TermsOfUse/TermsOfUseInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/TermsOfUse/TermsOfUseRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/TermsOfUse/TermsOfUseViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/TermsOfUse/View/TermsButton.swift
Labels: feature, UI, d-1

#56 스플레시, 로그인 화면 UI 업데이트
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIImageView+.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutViewController+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_pyonsnalColor.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_pyonsnalColor.imageset/Group 8896.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Splash/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Splash/image_splash.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Splash/image_splash.imageset/image_splash.png
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Splash/image_splash.imageset/image_splash@2x.png
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Splash/image_splash.imageset/image_splash@3x.png
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Temp/logo.imageset/logo.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Temp/splash_logo.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Temp/splash_logo.imageset/splash_logo.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Base.lproj/LaunchScreen.storyboard
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind+Icon.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind+Splash.swift
Labels: feature, UI, d-0

#59 자동 로그인 구현
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Application/AppComponent.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootComponent.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Service/KeyChainService.swift
  Pyonsnal-Color/Pyonsnal-Color/Service/UserAuthService.swift
  Pyonsnal-Color/Pyonsnal-Color/TermsOfUse/TermsOfUseInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/TermsOfUse/TermsOfUseViewController.swift
Labels: feature, d-1

#58 로그아웃, 탈퇴시 API 연동
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/AccountSetting/AccountSettingBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/AccountSetting/AccountSettingInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/AccountSetting/AccountSettingRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/AccountSetting/AccountSettingViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/CommonWeb/CommonWebBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/CommonWeb/CommonWebViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Member/MemberInfoEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedIn/LoggedInInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/LogoutPopup/LogoutPopupBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/LogoutPopup/LogoutPopupInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/LogoutPopup/LogoutPopupViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Model/EmptyResponse.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Config/Config.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Error/NetworkError.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Member/MemberAPI.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Member/MemberAPIService.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/PyonsnalColorClient.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarComponent.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/Service/KeyChainService.swift
  Pyonsnal-Color/Pyonsnal-Color/Service/UserAuthService.swift
Labels: feature, UI, d-0

#60 PB & 행사상품 조회 API연동
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ProductCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/ProductListDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/ConvenienceStore.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/EventTag.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/GiftItemEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/ProductEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Products/BrandProductEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Products/EventBannerEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Products/EventProductEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Products/PageableEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Products/ProductConvertable.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Products/ProductPageEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Products/SortEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/Cell/EventBannerCell.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/Cell/EventBannerItemCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Products/ProductAPI.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Products/ProductAPIService.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductListViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/tag_new.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/tag_new.imageset/Property 1=small.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Info.plist
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarComponent.swift
Labels: feature, d-0

#67 이벤트 탭, 프로파일 탭 자잘한 이슈 사항 수정
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ProductCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/TitleNavigationView.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Tag/NewTagBigView.swift
  Pyonsnal-Color/Pyonsnal-Color/CommonWeb/CommonWebBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/CommonWeb/CommonWebInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/CommonWeb/CommonWebViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/ConvenienceStore.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Products/ProductConvertable.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventDetail/EventDetailBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventDetail/EventDetailInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventDetail/EventDetailRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventDetail/EventDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeSectionLayout.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/Cell/EventBannerCell.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/Cell/EventBannerItemCell.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/ItemHeaderTitleView.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/String+.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductTagListView.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductListHeaderView.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/SettingInfo.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/tag_new.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/tag_new.imageset/Property 1=small.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Constants/CommonConstants.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Constants/Url/ProfileUrl.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Constants/Url/TermsOfUseUrl.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind.swift
Labels: bug, d-0

#70 Fix: 스크롤 후 update()시 타이머가 연속 설정되어 스크롤이 빨라지는 이슈 수정
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/Cell/EventBannerCell.swift
Labels: bug

#71 0.0.1 배포 준비
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Application/AppDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/AppIcon.appiconset/Frame 11.png
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/AppIcon.appiconset/Icon.png
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_7Eleven.imageset/7-eleven.png
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_7Eleven.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_7Eleven.imageset/icon_7Eleven.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_CU.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_CU.imageset/Property 1=CU.png
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_CU.imageset/icon_CU.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_Emart24.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_Emart24.imageset/Property 1=Emart24.png
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_Emart24.imageset/icon_Emart24.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_GS.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_GS.imageset/Property 1=GS.png
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_GS.imageset/icon_GS.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/GoogleService-Info.plist
Labels: feature, d-0

#72 상품 상세 화면 연결
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/BackNavigationView.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/ProductListDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Tag/NewTagBigView.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/ConvenienceStore.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventDetail/EventDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIImageView+.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/GiftItemView.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductTagListView.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductListViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeViewController.swift
Labels: feature, UI, d-0

#75 디자인 1차 QA 수정
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/Tag/NewTagBigView.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/EventTag.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductListViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarViewController.swift
Labels: bug, UI, design system, d-0

#78 이벤트 탭 데이터 로드하는 부분 수정
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
Labels: bug, d-0

#81 로그아웃 후 최초 로그인인지, 그 후 로그인인지 판별후 화면 이동 처리 추가
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Entity/Auth/UserLoginStatusEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Common/EmptyResponse.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Common/ErrorResponse.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Auth/AuthAPIService.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Auth/AuthRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/AuthType/AuthType.swift
  Pyonsnal-Color/Pyonsnal-Color/Service/KeyChainService.swift
Labels: feature, d-0

#77 탭바 선택시 상품 리스트 최상단으로 이동
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Pyonsnal-Color/Pyonsnal-Color/Common/ProductPresentable.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductListViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarViewController.swift
Labels: bug

#80 디자인 2차 QA
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/event.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/event.imageset/icon_tab_sale_unselected.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/event.selected.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/event.selected.imageset/icon_tab_sale.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/home.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/home.imageset/icon_tab_home_unselected.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/home.selected.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/home.selected.imageset/icon_tab_home_selected.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/profile.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/profile.imageset/icon_tab_my__unselected.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/profile.imageset/icon_tab_my_unselected.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/profile.selected.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/profile.selected.imageset/icon_tab_my.svg
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarViewController.swift
Labels: bug, feature, UI, d-0

#85 상품 홈/행사 화면에서 탭을 눌러 상단으로 이동 중 화면이 하얘지는 버그 수정
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
Labels: bug

#89 Feature/#87 search view UI
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/TitleNavigationView.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/TitleNavigationViewDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/SearchBar/SearchBarView.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/SearchBar/SearchBarViewDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIButton+.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchViewController+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_delete.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_delete.imageset/icon_delete.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_search.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_search.imageset/icon_search.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind+Icon.swift
Labels: feature, UI, d-1

#90 편의점 카테고리(PICK!), 카테고리 색상, 탭바 타이틀 변경
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ConvenienceStoreCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/TitleNavigationView.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/icon_title.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/icon_title.imageset/Layer_1.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Constants/CommonConstants.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind.swift
Labels: UI, d-1

#96 검색 화면 구현
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/EmptyCell+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/EmptyCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/ReusableView/LoadingReusableView+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/ReusableView/LoadingReusableView.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/SearchBar/SearchBarView.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UICollectionView+.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Products/ProductAPI.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Products/ProductAPIService.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchViewController+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchViewController.swift
Labels: feature, UI, d-0

#99 카테고리 관련 UI 추가 및 홈, 이벤트 탭 변경사항 적용
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/Button/FilterButton.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Button/PrimaryButton.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Button/SortButton.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/CategoryFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ConvenienceStoreCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/KeywordFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/RefreshFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Layout/CommonProductSectionLayout.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Layout/TopCommonSectionLayout.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Protocol/ClassNameRenderable.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Protocol/ItemIdentifier.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Protocol/ProductListDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Protocol/ProductPresentable.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Protocol/TopCollectionViewDatasource.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Protocol/ViewHolable.swift
  Pyonsnal-Color/Pyonsnal-Color/DesignSystem/Spacing.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/ConvenienceStore.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Filter/FilterCellItem.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Filter/FilterEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Filter/FilterType.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Filter/KeywordFilter.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/Cell/EventBannerCell.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/Cell/EventBannerItemCell.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/ItemHeaderTitleView.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/CGFloat+.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIButton+.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductListViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Filter/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Filter/icon_filter.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Filter/icon_filter.imageset/icon_filter.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Filter/icon_filter_refresh.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Filter/icon_filter_refresh.imageset/icon_revert.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Filter/icon_filter_view.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Filter/icon_filter_view.imageset/icon_filter_view.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Constants/CommonConstants.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAsset+Filter.swift
Labels: feature, UI, d-1

#103 필터 선택하는 바텀시트 구현
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/Button/FilterButton.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Button/SortButton.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ProductCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/RefreshFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Layout/TopCommonSectionLayout.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Filter/FilterCellItem.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Filter/FilterEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIView+.swift
  Pyonsnal-Color/Pyonsnal-Color/LogoutPopup/LogoutPopupViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/Cell/EventFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/Cell/RecommendFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/Cell/SortFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/ProductFilterBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/ProductFilterInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/ProductFilterRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/ProductFilterSectionLayout.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/ProductFilterViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/check.selected.red.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Common/check.selected.red.imageset/icon_check_selected.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind.swift
Labels: feature, UI, d-1

#106 필터 상태관리를 위한 구조 셋팅, 홈-이벤트 탭 버그 및 수정사항 반영
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Pyonsnal-Color/Pyonsnal-Color/Common/Button/FilterButton.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/CategoryFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/EmptyProductCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/KeywordFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ProductCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/RefreshFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/FilterStateManager.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Layout/CommonProductSectionLayout.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Protocol/ProductListDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/EventTag.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Filter/FilterCellItem.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Filter/FilterEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Filter/FilterType.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Filter/KeywordFilter.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Products/EventBannerEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/Cell/EventBannerCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Products/ProductAPI.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Products/ProductAPIService.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/PyonsnalColorClient.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/ProductFilterViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductListViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Constants/CommonConstants.swift
Labels: feature, UI, d-1
