Repository YAPP-Github/PyonsnalColor-iOS, pull requests merged in 2023-08, with the labels that each got.

#111 UI 공통 변경사항 수정
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ProductCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/TitleNavigationView.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductTagListView.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_pyonsnalColor.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_pyonsnalColor.imageset/Frame 8907.png
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_pyonsnalColor.imageset/Frame 8907@2x.png
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_pyonsnalColor.imageset/Frame 8907@3x.png
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_pyonsnalColor.imageset/Group 8896.svg
Labels: Common

#112 필터, 페이지네이션 로직 수정 및 큐레이션 페이지에서 필터 탭 히든 처리
  Pyonsnal-Color/Pyonsnal-Color/Common/Button/FilterButton.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/CategoryFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/KeywordFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/FilterStateManager.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Layout/TopCommonSectionLayout.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Protocol/ProductListDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Protocol/TopCollectionViewDatasource.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Filter/FilterCellItem.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Filter/FilterEntity.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Filter/FilterType.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/Cell/EventFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/Cell/RecommendFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/ProductFilterInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/ProductFilterViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductCurationViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductListViewController.swift
Labels: bug, d-0

#108 상품 검색 정렬 기능 구현
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/xcuserdata/gamza.xcuserdatad/xcschemes/xcschememanagement.plist
  Pyonsnal-Color/Pyonsnal-Color/Common/BottomSheet/BottomSheetDismissAnimator.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/BottomSheet/BottomSheetPresentationController.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/BottomSheet/BottomSheetPresentor.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/BottomSheet/BottomToTopPresentAnimator.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Button/SelectionButton.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Button/SortButton.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ProductCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/ReusableView/SearchFilterHeader+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/ReusableView/SearchFilterHeader.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/ReusableView/SearchFilterHeaderDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Products/ProductAPI.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Products/ProductAPIService.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/ProductFilterViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchViewController+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/SortBottomSheet/ProductSearchSortBottomSheetBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/SortBottomSheet/ProductSearchSortBottomSheetInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/SortBottomSheet/ProductSearchSortBottomSheetRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/SortBottomSheet/ProductSearchSortBottomSheetViewController+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/SortBottomSheet/ProductSearchSortBottomSheetViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_check.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/Icon/icon_check.imageset/icon_check.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind+Icon.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind.swift
Labels: feature, d-1

#114 키보드 숨김 로직 추가
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIView+.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchViewController+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchViewController.swift
Labels: d-0

#118 홈 화면에서 상품 로드시 최상단으로 이동하는 버그 수정
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
Labels: bug, d-0

#120 디자인 QA 0.0.2
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/KeywordFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ProductCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/Layout/CommonProductSectionLayout.swift
  Pyonsnal-Color/Pyonsnal-Color/Common/NavigationBar/TitleNavigationView.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIFont+.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutViewController+ViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/Cell/RecommendFilterCell.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/CurationSectionLayout.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Lottie/main.json
Labels: UI
