Repository YAPP-Github/PyonsnalColor-iOS, pull requests merged in 2023-06, with the labels that each got.

#7 카카오 로그인 서비스 추가
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Pyonsnal-Color/Pyonsnal-Color/Application/SceneDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Info.plist
  Pyonsnal-Color/Pyonsnal-Color/Root/RootComponent+LoggedOut.swift
  Pyonsnal-Color/Pyonsnal-Color/Service/KakaoLoginService.swift
Labels: feature, d-n

#9 프로젝트에 필요한 라이브러리 추가 및 확장 기능 추가
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/xcuserdata/gamza.xcuserdatad/xcschemes/xcschememanagement.plist
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIButton+.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIImageView+.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/URLRequest+.swift
  Pyonsnal-Color/Pyonsnal-Color/Networking/Auth/AuthRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/ImageAssetKind/ImageAssetKind.swift
Labels: feature, d-n

#13 UIFont extension 추가
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIFont+.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Font/Pretendard-Medium.otf
  Pyonsnal-Color/Pyonsnal-Color/Resource/Font/Pretendard-Regular.otf
  Pyonsnal-Color/Pyonsnal-Color/Resource/Font/Pretendard-SemiBold.otf
  Pyonsnal-Color/Pyonsnal-Color/Resource/Info.plist
Labels: design system, d-1

#15 LoggedIn & RootTabBar RIB 구현
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Pyonsnal-Color/Pyonsnal-Color/Application/SceneDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/CALayer+.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedIn/LoggedInBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedIn/LoggedInInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedIn/LoggedInRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootComponent+LoggedOut.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootComponent.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/Root/RootViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarComponent.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarRouter.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Service/KakaoLoginService.swift
Labels: feature, UI, d-1

#17 앱 배포 준비
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/AppIcon.appiconset/Icon.png
Labels: feature, d-n

#19 상품 cell - ProductItemCardCell UI 추가
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ProductCell.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/NSMutableAttributedString+.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/String+.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIFont+.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UIView+.swift
Labels: UI, d-1

#20 PR 템플릿 양식 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: d-n

#21 홈 탭 화면 구현 - ProductHome
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/Common/Cell/ConvenienceStoreCell.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Extension/UICollectionView+.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductHomePageViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductListHeaderView.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductListViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/event.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/event.imageset/icon_tab_sale_unselected.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/event.selected.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/event.selected.imageset/icon_tab_sale.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/home.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/home.imageset/icon_tab_home_unselected.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/home.selected.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/home.selected.imageset/icon_tab_home_selected.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/profile.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/profile.imageset/icon_tab_my__unselected.svg
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/profile.selected.imageset/Contents.json
  Pyonsnal-Color/Pyonsnal-Color/Resource/Assets.xcassets/TabBar/profile.selected.imageset/icon_tab_my.svg
Labels: feature, UI, d-n
