Repository YAPP-Github/PyonsnalColor-iOS, pull requests merged in 2024-01, with the labels that each got.

#153 Feature/#152 user logging
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/3rdParty/Firebase+.swift
  Pyonsnal-Color/Pyonsnal-Color/AccountSetting/AccountSettingViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/CommonWeb/CommonWebViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/DetailReviewViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventDetail/EventDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/EventHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/EventHome/Views/EventHomeTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/FavoriteHome/View/FavoriteHomePageTabViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/FavoriteHome/View/FavoriteHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/LoggedOut/LoggedOutViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductDetail/ProductDetailViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/ProductFilterViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/ProductHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductCurationViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductListViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductSearch/ProductSearchViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/ProfileHome/ProfileHomeViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/RootTabBar/RootTabBarViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/StarRatingReview/StarRatingReviewViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/TermsOfUse/TermsOfUseViewController.swift
Labels: feature, d-1

#158 0.9(1) 기능 QA 및 0.2(3) 디자인 QA
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/DetailReviewBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/DetailReviewInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/DetailReviewViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/DetailReviewViewHolder.swift
  Pyonsnal-Color/Pyonsnal-Color/DetailReview/Views/SingleLineReview.swift
  Pyonsnal-Color/Pyonsnal-Color/Entity/Review/UserReviewInput.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductFilter/ProductFilterViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/StarRatingReview/StarRatingReviewBuilder.swift
  Pyonsnal-Color/Pyonsnal-Color/StarRatingReview/StarRatingReviewInteractor.swift
  Pyonsnal-Color/Pyonsnal-Color/StarRatingReview/StarRatingReviewRouter.swift
Labels: UI, QA

#160 구글 애드몹 - 큐레이션 중간 광고 추가
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.pbxproj
  Pyonsnal-Color/Pyonsnal-Color.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Pyonsnal-Color/Pyonsnal-Color/Application/AppDelegate.swift
  Pyonsnal-Color/Pyonsnal-Color/Manager/AdMobManager.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/Cell/CurationAdCell.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/Cell/NativeAdView.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/CurationSectionLayout.swift
  Pyonsnal-Color/Pyonsnal-Color/ProductHome/Views/ProductCurationViewController.swift
  Pyonsnal-Color/Pyonsnal-Color/Resource/Info.plist
  Pyonsnal-Color/Pyonsnal-Color/Service/UserInfoService.swift
Labels: feature, d-1

#162 유니버셜 링크 대응
  Pyonsnal-Color/Pyonsnal-Color/Pyonsnal-Color.entitlements
Labels: feature
